name: iOS IPA Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      # Pods
      - run: |
          cd ios
          pod install

      # Archive
      - name: Archive
        run: |
          npm run ios

      # 导出 IPA
      - name: Export IPA
        run: |
          cd ios

          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/FeehiApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

      # 上传
      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/ipa
